version: '3'

services:

  db:
    image: mysql:5.7.16
    command: --innodb-use-native-aio=0 --init-file /docker-entrypoint-initdb.d/init.sql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network  

  app:
    build: 
      context: ./node
      dockerfile: Dockerfile
    image: rafael8paulo/app-node
    container_name: app
    entrypoint: sh -c "npm install && dockerize -wait tcp://db:3306 --timeout 50s node index.js"
    networks:
      - app-network
    volumes:
      - ./node:/usr/src/app/
    tty: true
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: rafael8paulo/app-nginx
    container_name: nginx
    networks:
      - app-network
    ports:
      - "8080:80"
    tty: true
    depends_on:
      - app

networks:
  app-network:
    driver: bridge